INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('ABACATE', 'PERSEA GRATISSIMA OU LAURUS PERSEA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('ABACAXI', 'ANANAS SATIVUS');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('ABIU', 'POUTERIA CAIMITO');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('AÇAÍ', 'EUTERPE OLERACEA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('ACEROLA', 'MALPIGHIA GLABRA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('AMEIXA', 'PRUNUS DOMESTICA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('AMORA', 'MORUS NIGRA OU MORUS ALBA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('ARAÇÁ', 'PSIDIUM ARAÇA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('ARATICUM', 'ANNONA CRASSIFLORA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('BANANA', 'MUSASP');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('BUTIÁ', 'BUTIA PARAGUAYENSIS');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('CACAU', 'THEOBROMA CACAO');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('CAJÁ', 'SPONDIAS LUTEA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('CAJÚ', 'ANACARDIUM OCCIDENTALE');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('CAQUI', 'DIOSPYRUS KAKI');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('CARAMBOLA', 'AVEHRROA CARAMBOLA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('CEREJA', 'PRUNUS CERASUS');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('CÔCO', 'COCOS NUCIFERA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('CUPUAÇÚ', 'THEOBROMA GRANDIFLORUM');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('DAMASCO', 'PRUNUS ARMENIACA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('FIGO', 'FICUS CARICA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('FRUTA DO CONDE', 'ANNONA SQUAMOSA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('GOIABA', 'PSIDIUM GUAYAVA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('GRAVIOLA', 'ANNONA MURICATA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('GUABIROBA', 'CAMPOMANESIA XANTOCARPA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('INGÁ', 'INGA EDULIS');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('JABUTICABA', 'MYRCIARIA JABOTICABA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('JACA', 'ARTOCARPUS INTEGRIFOLIA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('KIWI', 'ACTINIA CHINENSIS');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('LARANJA', 'CITRUS SINENSIS');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('LIMA', 'CITRUS LIMETTA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('LIMÃO', 'CITRUS LIMONUM');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('MAÇÃ', 'MALUSSP');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('MAMÃO', 'CARICA PAPAYA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('MANGA', 'MANGIFERA INDICA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('MANGABA', 'HANCORNIA SPECIOSA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('MARACUJÁ', 'PASSIFLORASP');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('MELANCIA', 'CITRULUS VULGARIS');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('MELÃO', 'CUCUMIS MELO');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('MORANGO', 'FRAGARIA VESCA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('NÊSPERA', 'ERIOBOTRYA JAPONICA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('PERA', 'PYRUS COMMUNIS');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('PÊSSEGO', 'PRUNUS PERSICA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('PITANGA', 'EUGENIA UNIFLORA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('ROMÃ', 'PUNICA GRANATUM');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('SAPOTI', 'MATISSIA CORDATA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('TÂMARA', 'PHOENIX DACTYLIFERA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('TAMARINO', 'TAMARINDUS INDICA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('TANGERINA', 'CITRUS NOBILIS');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('UMBÚ', 'SPONDIAS TUBEROSA');
INSERT INTO pgd.tb_fruta (nome, nome_cientifico) VALUES ('UVA', 'VITIS VINIFERA');

